### ISSUE TITLE
PHP Fatal error: NotAuthenticated

### ISSUE THREAD

**Issue by RhanCandia** [hitrov/oci-arm-host-capacity#101]
Can't make the script work.

```
PHP Fatal error:  Uncaught Hitrov\Exception\ApiCallException: {
    "code": "NotAuthenticated",
    "message": "The required information to complete authentication was not provided or was incorrect."
} in /home/ubuntu/oci-arm-host-capacity/src/HttpClient.php:42
Stack trace:
#0 /home/ubuntu/oci-arm-host-capacity/src/OciApi.php(257): Hitrov\HttpClient::getResponse()
#1 /home/ubuntu/oci-arm-host-capacity/src/OciApi.php(132): Hitrov\OciApi->call()
#2 /home/ubuntu/oci-arm-host-capacity/index.php(74): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in /home/ubuntu/oci-arm-host-capacity/src/HttpClient.php on line 42
```

**Comment by RhanCandia** [comment]
Weird. I generated an new key and that worked.
