### ISSUE TITLE
Uncaught Hitrov\Exception\CurlException: curl error occurred: SSL certificate problem: unable to get local issuer certificate, response:  in C:\Users\Palicz\Downloads\setup\oci-arm-host-capacity\src\HttpClient.php:31

### ISSUE THREAD

**Issue by palicz** [hitrov/oci-arm-host-capacity#116]
### Hey guys.
Anyone could help me with this error?
```
PHP Fatal error:  Uncaught Hitrov\Exception\CurlException: curl error occurred: SSL certificate problem: unable to get local issuer certificate, response:  in C:\Users\Palicz\Downloads\setup\oci-arm-host-capacity\src\HttpClient.php:31
Stack trace:
#0 C:\Users\Palicz\Downloads\setup\oci-arm-host-capacity\src\OciApi.php(257): Hitrov\HttpClient::getResponse()
#1 C:\Users\Palicz\Downloads\setup\oci-arm-host-capacity\src\OciApi.php(132): Hitrov\OciApi->call()
#2 C:\Users\Palicz\Downloads\setup\oci-arm-host-capacity\index.php(74): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in C:\Users\Palicz\Downloads\setup\oci-arm-host-capacity\src\HttpClient.php on line 31
```

**Comment by HJRaptor** [comment]
how did you fix this?
