### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Karelak** [hitrov/oci-arm-host-capacity#117]
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an unexpected escape sequence at ["C:\Users\Kaarel\oci-arm-host-capacity\key.pem"]. in C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Parser\Parser.php:30 Stack trace: #0 C:\Users\Kaarel\oci-arm-host-capacity\vendor\graham-campbell\result-type\src\Error.php(119): Dotenv\Parser\Parser::Dotenv\Parser\{closure}() #1 C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Parser\Parser.php(29): GrahamCampbell\ResultType\Error->mapError() #2 C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Dotenv.php(222): Dotenv\Parser\Parser->parse() #3 C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Dotenv.php(237): Dotenv\Dotenv->load() #4 C:\Users\Kaarel\oci-arm-host-capacity\index.php(19): Dotenv\Dotenv->safeLoad() #5 {main}   thrown in C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Parser\Parser.php on line 30

**Comment by Karelak** [comment]
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an unexpected escape sequence at ["C:\Users\Kaarel\oci-arm-host-capacity\key.pem"]. in C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Parser\Parser.php:30 Stack trace: #0 C:\Users\Kaarel\oci-arm-host-capacity\vendor\graham-campbell\result-type\src\Error.php(119): Dotenv\Parser\Parser::Dotenv\Parser\{closure}() #1 C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Parser\Parser.php(29): GrahamCampbell\ResultType\Error->mapError() #2 C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Dotenv.php(222): Dotenv\Parser\Parser->parse() #3 C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Dotenv.php(237): Dotenv\Dotenv->load() #4 C:\Users\Kaarel\oci-arm-host-capacity\index.php(19): Dotenv\Dotenv->safeLoad() #5 {main}   thrown in C:\Users\Kaarel\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Parser\Parser.php on line 30
