### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined constant "Hitrov\CURLOPT_URL" in /home/asnct/oci-arm-host-capacity/src/OciApi.php:243

### ISSUE THREAD

**Issue by asnct** [hitrov/oci-arm-host-capacity#122]
After I filled out the .env according to the instructions in the README, I try to run the script and get this:

```
PHP Fatal error:  Uncaught Error: Undefined constant "Hitrov\CURLOPT_URL" in /home/asnct/oci-arm-host-capacity/src/OciApi.php:243
Stack trace:
#0 /home/asnct/oci-arm-host-capacity/src/OciApi.php(132): Hitrov\OciApi->call()
#1 /home/asnct/oci-arm-host-capacity/index.php(74): Hitrov\OciApi->getInstances()
#2 {main}
  thrown in /home/asnct/oci-arm-host-capacity/src/OciApi.php on line 243
```

**Comment by heliopr** [comment]
what did you do to solve this?

**Comment by asnct** [comment]
> what did you do to solve this? I'm getting the same error

I installed php-curl
