### ISSUE TITLE
Fatal error:  Uncaught Hitrov\Exception\ApiCallException: {     "code": "NotAuthenticated",     "message": "Failed to verify the HTTP(S) Signature" } in /home/ubuntu/oci-arm-host-capacity/src/HttpClient.php:42

### ISSUE THREAD

**Issue by desioxss** [hitrov/oci-arm-host-capacity#127]
`PHP Fatal error:  Uncaught Hitrov\Exception\ApiCallException: {`
`    "code": "NotAuthenticated",`
`    "message": "Failed to verify the HTTP(S) Signature"`
`} in /home/ubuntu/oci-arm-host-capacity/src/HttpClient.php:42`
`Stack trace:`
`#0 /home/ubuntu/oci-arm-host-capacity/src/OciApi.php(257): Hitrov\HttpClient::getResponse()`
`#1 /home/ubuntu/oci-arm-host-capacity/src/OciApi.php(132): Hitrov\OciApi->call()`
`#2 /home/ubuntu/oci-arm-host-capacity/index.php(74): Hitrov\OciApi->getInstances()`
`#3 {main}`
`  thrown in /home/ubuntu/oci-arm-host-capacity/src/HttpClient.php on line 42`

I get this when running "php index.php" on micro instance for flex instance, what should I do?

**Comment by HexHands** [comment]
I believe the issue is that the private key file that you gave was incorrect. You need to use the private key file obtained from creating the API key.
