### ISSUE TITLE
Where do i download and install Dependencies? ALSO: composer ERROR.

### ISSUE THREAD

**Issue by Genious28** [hitrov/oci-arm-host-capacity#130]
I'm too tired trying to make this work, so here's the error;
I have **PhP v8.3.6** installed.. and i tried both` pip install composer` and downloading a `composer-setup.exe` from the web.

```
C:\Users\JS-Technologies\oci-arm-host-capacity>composer install
C:\Tools\Compilers&Interpreters\Python\3.12.2\python.exe: can't open file 'C:\\Users\\JS-Technologies\\oci-arm-host-capacity\\install': [Errno 2] No such file or directory
ERROR:composer.cli.launcher:Rank 0 crashed with exit code 2.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Tools\Compilers&Interpreters\Python\3.12.2\Scripts\composer.exe\__main__.py", line 7, in <module>
  File "C:\Tools\Compilers&Interpreters\Python\3.12.2\Lib\site-packages\composer\cli\launcher.py", line 578, in main
    _cleanup_processes(processes)
  File "C:\Tools\Compilers&Interpreters\Python\3.12.2\Lib\site-packages\composer\cli\launcher.py", line 502, in _cleanup_processes
    if -process.returncode in (signal.SIGKILL, signal.SIGTERM):
                               ^^^^^^^^^^^^^^
AttributeError: module 'signal' has no attribute 'SIGKILL'. Did you mean: 'SIGILL'?
```

**Comment by pomazanbohdan** [comment]
https://pypi.org/project/composer ??

del hem

**Comment by pomazanbohdan** [comment]
https://stackoverflow.com/questions/25549177/change-composer-global-path-windows

**Comment by Genious28** [comment]
Ah, that was dumb of me.. Sorry, like i said, i was too tired to solve it at that time. I spent like 14 hrs writing a 2 AI models and training it, and also evaluating them.
