### ISSUE TITLE
Getting issue when running index.php

### ISSUE THREAD

**Issue by Croep** [hitrov/oci-arm-host-capacity#143]
PHP Fatal error:  Uncaught Hitrov\Exception\CurlException: curl error occurred: SSL certificate problem: unable to get local issuer certificate, response:  in C:\Users\***\oci-arm-host-capacity\src\HttpClient.php:31
Stack trace:
#0 C:\Users\***\oci-arm-host-capacity\src\OciApi.php(257): Hitrov\HttpClient::getResponse()
#1 C:\Users\***\oci-arm-host-capacity\src\OciApi.php(132): Hitrov\OciApi->call()
#2 C:\Users\***\oci-arm-host-capacity\index.php(74): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in C:\Users\***\oci-arm-host-capacity\src\HttpClient.php on line 31

**Comment by Croep** [comment]
nvm i fixed it using this thread https://github.com/hitrov/oci-arm-host-capacity/issues/124
