### ISSUE TITLE
Curl error occurred: SSL certificate problem?

### ISSUE THREAD

**Issue by Rtchyc** [hitrov/oci-arm-host-capacity#46]
### I get the SSL error, the information for the script is all OK
I use WINDOWS

```
PHP Fatal error:  Uncaught Hitrov\Exception\CurlException: curl error occurred: SSL certificate problem: unable to get local issuer certificate, response:  in C:\Users\NAME\Downloads\oracle\oci-arm-host-capacity\src\HttpClient.php:31
Stack trace:
#0 C:\Users\NAME\Downloads\oracle\oci-arm-host-capacity\src\OciApi.php(210): Hitrov\HttpClient::getResponse(Array)
#1 C:\Users\NAME\Downloads\oracle\oci-arm-host-capacity\src\OciApi.php(102): Hitrov\OciApi->call(Object(Hitrov\OciConfig), 'https://iaas.us...', 'GET', NULL, Array)
#2 C:\Users\NAME\Downloads\oracle\oci-arm-host-capacity\index.php(66): Hitrov\OciApi->getInstances(Object(Hitrov\OciConfig))
```

What can it be?

**Comment by Rtchyc** [comment]
> that's common issue on fresh local environment, google it

I've already tried searching and haven't found any solution that works.
how should i search?

**Comment by hitrov** [comment]
https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

**Comment by Rtchyc** [comment]
> https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

sorry, but I can't, I have no idea what it is
