### ISSUE TITLE
Whats the error

### ISSUE THREAD

**Issue by Ajvj09** [hitrov/oci-arm-host-capacity#49]
![Uploading IMG_20220910_154742.jpg…]()

**Comment by Ajvj09** [comment]
![IMG_20220910_154742](https://user-images.githubusercontent.com/106460363/189478940-d8973c9d-44bc-49a0-bd97-803988e6d550.jpg)

**Comment by bbauti** [comment]
I'm having the same problem, any solution?
`PHP Fatal error:  Uncaught Hitrov\Exception\CurlException: curl error occurred: Resolving timed out after 10000 milliseconds, response:  in /home/bbauti/oci-arm-host-capacity/src/HttpClient.php:31

Stack trace:
#0 /home/bbauti/oci-arm-host-capacity/src/OciApi.php(210): Hitrov\HttpClient::getResponse()
#1 /home/bbauti/oci-arm-host-capacity/src/OciApi.php(102): Hitrov\OciApi->call()
#2 /home/bbauti/oci-arm-host-capacity/index.php(66): Hitrov\OciApi->getInstances()
#3 {main}
thrown in /home/bbauti/oci-arm-host-capacity/src/HttpClient.php on line 31`

**Comment by RaistlinTAO** [comment]
Whatever env you are currently using cannot connect to the oracle cloud,

**Comment by HanosThePlacid** [comment]
I have the same issue. 
![Capture](https://github.com/hitrov/oci-arm-host-capacity/assets/74451470/71790ce0-2915-4111-b039-57e11a5d3515)
Could you elaborate on what you mean by _"Whatever env you are currently using cannot connect to the oracle cloud,"_
I'm pretty new to linux, php, and to programming in general. 
Is my .env file faulty? or did you mean enviroment?

And what shall I do to fix it?

**Comment by RaistlinTAO** [comment]
> I have the same issue. ![Capture](https://private-user-images.githubusercontent.com/74451470/296413163-71790ce0-2915-4111-b039-57e11a5d3515.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTg3MzgsIm5iZiI6MTcwNTIxODQzOCwicGF0aCI6Ii83NDQ1MTQ3MC8yOTY0MTMxNjMtNzE3OTBjZTAtMjkxNS00MTExLWIwMzktNTdlMTFhNWQzNTE1LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA3NDcxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYjg2ZTc1ZWY0MDI3ZWI4YmVhNmQ4YjgzNTkwMDZmNzA0ZjFjN2JmZjZmZDI2ZDg4OTIwNzQ0NDhkMzQyMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tL1CD7Kw3tRoTHPVPyF2moTacxPGoNTP4NKGZJteARE) Could you elaborate on what you mean by _"Whatever env you are currently using cannot connect to the oracle cloud,"_ I'm pretty new to linux, php, and to programming in general. Is my .env file faulty? or did you mean enviroment?
> 
> And what shall I do to fix it?

Certainly, based on the error information captured in your screenshot, it appears that the OciApi is encountering an issue when attempting to resolve iaas.amsterdam-1.oraclecloud.com during the initialization of an instance with HttpClient. 
This indicates that your runtime environment (referred to as "env") lacks a suitable DNS configuration to resolve this domain. 

You can perform the following troubleshooting steps:

1. Try to ping or curl the domain directly in Linux. if dns cannot be solved, edit /etc/hosts directly or fix any firewall related permission issues.
2. Please double-check the Oracle Cloud dashboard to confirm whether the API address is indeed set to 'iaas.amsterdam-1.oraclecloud.com'. 
In the source code, the developer utilizes
`private function getBaseApiUrl(OciConfig $config, string $api = 'iaas'): string
    {
        return "https://$api.{$config->region}.oraclecloud.com/20160918";
    }` to generate api addresses.

If your API address is incorrect, it could be due to an error in the region configuration, or Oracle Cloud might have changed the API access address for your specific region. Verify the accuracy of the API address by checking the region configuration, and make sure it aligns with the correct API access address provided by Oracle Cloud.
