### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Hitrov\OciConfig::__construct() must be of the type string

### ISSUE THREAD

**Issue by gerddasboot** [hitrov/oci-arm-host-capacity#56]
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Hitrov\OciConfig::__construct() must be of the type string, bool given, called in /app/oci-arm-host-capacity/index.php on line 36 and defined in /app/oci-arm-host-capacity/src/OciConfig.php:44
Stack trace:
#0 /app/oci-arm-host-capacity/index.php(36): Hitrov\OciConfig->__construct()
#1 {main}
  thrown in /app/oci-arm-host-capacity/src/OciConfig.php on line 44
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Hitrov\OciConfig::__construct() must be of the type string, bool given, called in /app/oci-arm-host-capacity/index.php on line 36 and defined in /app/oci-arm-host-capacity/src/OciConfig.php:44
Stack trace:
#0 /app/oci-arm-host-capacity/index.php(36): Hitrov\OciConfig->__construct()
#1 {main}
  thrown in /app/oci-arm-host-capacity/src/OciConfig.php on line 44
2022-12-13_15-32-44 - -
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Hitrov\OciConfig::__construct() must be of the type string, bool given, called in /app/oci-arm-host-capacity/index.php on line 36 and defined in /app/oci-arm-host-capacity/src/OciConfig.php:44
Stack trace:
#0 /app/oci-arm-host-capacity/index.php(36): Hitrov\OciConfig->__construct()
#1 {main}
  thrown in /app/oci-arm-host-capacity/src/OciConfig.php on line 44
2022-12-13_15-42-45 - -
`

I really don't know where this comes from. Everything in .env that should be a string is an string and not bool.

Kind regards

**Comment by mtik** [comment]
Having same problem!

**Comment by phamchin** [comment]
I had the same problem
My config parameter is the same as in the video guide on Youtube
![image](https://github.com/hitrov/oci-arm-host-capacity/assets/30959912/5546e573-dcf4-49df-b035-a0b0778d54cb)
