### ISSUE TITLE
PHP Help Needed !

### ISSUE THREAD

**Issue by speedforce-demo** [hitrov/oci-arm-host-capacity#62]
PHP Warning:  openssl_sign(): supplied key param cannot be coerced into a private key in /var/www/html/uamd/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php on line 99
PHP Fatal error:  Uncaught Hitrov\OCI\Exception\SigningValidationFailedException: Cannot generate signature. in /var/www/html/uamd/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php:101
Stack trace:
#0 /var/www/html/uamd/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php(72): Hitrov\OCI\Signer->calculateSignature()
#1 /var/www/html/uamd/src/OciApi.php(193): Hitrov\OCI\Signer->getHeaders()
#2 /var/www/html/uamd/src/OciApi.php(102): Hitrov\OciApi->call()
#3 /var/www/html/uamd/index.php(66): Hitrov\OciApi->getInstances()
#4 {main}
  thrown in /var/www/html/uamd/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php on line 101
  
  How can I solve this error ?

**Comment by hitrov** [comment]
I believe it’s straightforward, something wrong with private key (file), try local (path) if you’re using URL and vice versa otherwise

**Comment by speedforce-demo** [comment]
OCI_PRIVATE_KEY_FILENAME="-03-12-19-05.pem"
OCI_SSH_PUBLIC_KEY="key.pub"

l used files like this.

**Comment by RaistlinTAO** [comment]
> OCI_PRIVATE_KEY_FILENAME="-03-12-19-05.pem" OCI_SSH_PUBLIC_KEY="key.pub"
> 
> l used files like this.


For OCI_PRIVATE_KEY_FILENAME, you should including the path as well like
`
"/home/roo/oci/exxx@xxx.com_2022-03-26T16_39_05.568Z.pem"
`

And OCI_SSH_PUBLIC_KEY should be your public key contents, not the path, something like

`OCI_SSH_PUBLIC_KEY="ssh-rsa AAAsadfsdfQrIJZsdfsdsdafsdafasfszxczvcasdfdgf9$`

I think the .env is pretty self explained

**Comment by wangshiok** [comment]
> OCI_PRIVATE_KEY_FILENAME="-03-12-19-05.pem" OCI_SSH_PUBLIC_KEY="key.pub"
> 
> l used files like this.

have you got it fixed? I got the same issue here, stuck for days now.
OCI_SSH_PUBLIC_KEY="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFP0/ozTqbEM1ibEJuydtuMenDARz775xc7/HcWoUkaC ubuntu@ubuntu3"

**Comment by RaistlinTAO** [comment]
> PHP Warning: openssl_sign(): supplied key param cannot be coerced into a private key in /var/www/html/uamd/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php on line 99
> PHP Fatal error: Uncaught Hitrov\OCI\Exception\SigningValidationFailedException: Cannot generate signature. in /var/www/html/uamd/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php:101
> Stack trace:
> #0 /var/www/html/uamd/vendor/hitrov/oci-api-php-request-sign/src/Hitrov/OCI/Signer.php(72): Hitrov\OCI\Signer->calculateSignature()

The error indicates that either private key or public key is wrong or cannot access.

Try the following steps for troubleshooting:
1. Verify the public key/key file pair. You must make sure they are corresponding.
2. Verify the path is correct, you can use readlink or realpath to verify
3. Done

**Comment by hitrov** [comment]
Try also setting file permissions `sudo chmod 777 /path/to/file.pem`

**Comment by 111100001** [comment]
same issue tried to do all what you said but it still persists

**Comment by 111100001** [comment]
never mind i solved it.

 we need to put the private key of the Api key into the OCI_PRIVATE_KEY_FILENAME . I was putting the SSH private key here because dumb dumb.
