### ISSUE TITLE
PHP Warning after php ./index.php

### ISSUE THREAD

**Issue by SailTheWorldBy50** [hitrov/oci-arm-host-capacity#64]
When I run `php ./index.php` I'm getting:

```PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /home/rob/oci-arm-host-capacity/index.php on line 8
PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php') in /home/rob/oci-arm-host-capacity/index.php on line 8```

Do you have any idea what I'm doing wrong?

**Comment by hitrov** [comment]
https://stackoverflow.com/questions/41209349/requirevendor-autoload-php-failed-to-open-stream

**Comment by hitrov** [comment]
https://github.com/hitrov/oci-arm-host-capacity#installation

**Comment by SailTheWorldBy50** [comment]
```
rob@rdnas:~/oci-arm-host-capacity$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-curl * is missing from your system. Install or enable PHP's curl extension.
  Problem 2
    - Installation request for phar-io/manifest 2.0.3 -> satisfiable by phar-io/manifest[2.0.3].
    - phar-io/manifest 2.0.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 3
    - Installation request for phpunit/php-code-coverage 9.2.17 -> satisfiable by phpunit/php-code-coverage[9.2.17].
    - phpunit/php-code-coverage 9.2.17 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 4
    - Installation request for phpunit/phpunit 9.5.25 -> satisfiable by phpunit/phpunit[9.5.25].
    - phpunit/phpunit 9.5.25 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 5
    - Installation request for theseer/tokenizer 1.2.1 -> satisfiable by theseer/tokenizer[1.2.1].
    - theseer/tokenizer 1.2.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
rob@rdnas:~/oci-arm-host-capacity$
```

**Comment by hitrov** [comment]
Check my video https://youtu.be/uzAqgjElc64

**Comment by SailTheWorldBy50** [comment]
Thanks I saw in the description the instructions to install PHP and followed them. Now i'm getting: 
```
PHP Fatal error:  Uncaught Hitrov\Exception\ApiCallException: {
    "code": "NotAuthenticated",
    "message": "The required information to complete authentication was not provided or was incorrect."
} in /home/rob/oci-arm-host-capacity/src/HttpClient.php:42
Stack trace:
#0 /home/rob/oci-arm-host-capacity/src/OciApi.php(210): Hitrov\HttpClient::getResponse()
#1 /home/rob/oci-arm-host-capacity/src/OciApi.php(102): Hitrov\OciApi->call()
#2 /home/rob/oci-arm-host-capacity/index.php(66): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in /home/rob/oci-arm-host-capacity/src/HttpClient.php on line 42
```
That sounds like I filled in the .env wrong.

**Comment by SailTheWorldBy50** [comment]
Must have had an extra space in one field. Recopied and now
```
rob@rdnas:~/oci-arm-host-capacity$ php ./index.php
{
    "code": "InternalError",
    "message": "Out of host capacity."
}
{
    "code": "InternalError",
    "message": "Out of host capacity."
}
{
    "code": "InternalError",
    "message": "Out of host capacity."
}
```
Thanks for your quick help!
