### ISSUE TITLE
PHP Fatal error Uncaught Hitrov

### ISSUE THREAD

**Issue by ForDefault** [hitrov/oci-arm-host-capacity#76]
So I have gotten this on different computers. I am assuming its my keys, but I followed the guide/video. Made sure permissions are right for the .pem and I have tried making the .pem a relative location in the .env

Is there something I was suppose to do to activate the api? The remote server part threw me- I assumed it was not Oracle but a private Ubuntu being connected to for the video. Otherwise I have no idea how you got the IP [YoutubeVideo](https://www.youtube.com/watch?v=uzAqgjElc64)

```
```
PHP Fatal error:  Uncaught Hitrov\Exception\ApiCallException: {
    "code": "NotAuthenticated",
    "message": "The required information to complete authentication was not provided or was incorrect."
} in /home/wego/oci-arm-host-capacity/src/HttpClient.php:42
Stack trace:
#0 /home/wego/oci-arm-host-capacity/src/OciApi.php(257): Hitrov\HttpClient::getResponse()
#1 /home/wego/oci-arm-host-capacity/src/OciApi.php(132): Hitrov\OciApi->call()
#2 /home/wego/oci-arm-host-capacity/index.php(74): Hitrov\OciApi->getInstances()
#3 {main}
  thrown in /home/wego/oci-arm-host-capacity/src/HttpClient.php on line 42

```
OCI_REGION=ca-toronto-1
OCI_USER_ID=ocid1.user.oc1..a*****q
OCI_TENANCY_ID=ocid1.tenancy.oc1..aaaa*****a
OCI_KEY_FINGERPRINT=1********c

# absolute path (including directories) or direct public accessible URL
OCI_PRIVATE_KEY_FILENAME="/home/***/oci-arm-host-capacity/f****@***mail.com.pem"
OCI_SUBNET_ID=ocid1.subnet.oc1.ca-toronto-1.**
OCI_IMAGE_ID=ocid1.image.oc1.ca-toronto-1.**

# Always free ARM: 1,2,3,4. Always free AMD x64: 1
OCI_OCPUS=4

# Always free ARM: 6,12,18,24. NB! Oracle Linux Cloud Developer Image requires minimum 8. Always free AMD x64: 1
OCI_MEMORY_IN_GBS=24

# Or "VM.Standard.E2.1.Micro" for Always free AMD x64
OCI_SHAPE=VM.Standard.A1.Flex
OCI_MAX_INSTANCES=1

# Your public key ~/.ssh/id_rsa.pub contents
# NB! No new lines / line endings allowed! Put inside double quotes
OCI_SSH_PUBLIC_KEY="ssh-rsa A******************************************************E= **@**"

# Is now optional for ARM since Always Free ARMs can be created in any AD.
# ListAvailabilityDomains API call will be used for retrieval https://docs.oracle.com/en-us/iaas/api/#/en/identity/20160918/AvailabilityDomain/ListAvailabilityDomains
#
# NB! Always free AMD x64 instances should be created only in "main" (Always Free Eligible) AD,
# you must set it manually in this case!
#
# If you wanna specify more than one, set as a PHP array in OciConfig constructor (inside index.php file)
OCI_AVAILABILITY_DOMAIN=

CACHE_AVAILABILITY_DOMAINS=1

# Optional. If not set, default value depends on OCI_IMAGE_ID will be used.
# Minimum is 47 for AMD x64 or 50 for ARM, maximum is 200 for Always Free accounts
OCI_BOOT_VOLUME_SIZE_IN_GBS=200

# Optional. If set, will be used instead OCI_IMAGE_ID. Cannot be used together with OCI_BOOT_VOLUME_SIZE_IN_GBS.
# Open https://cloud.oracle.com/block-storage/boot-volumes, click non-used and copy it's OCID
# NB! You must specify OCI_AVAILABILITY_DOMAIN also as they should be located in the same one
OCI_BOOT_VOLUME_ID=

TOO_MANY_REQUESTS_TIME_WAIT=600
```

**Comment by palicz** [comment]
I have the same issue.. any advice?
