### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by SARCASMISH** [hitrov/oci-arm-host-capacity#79]
Tried `php <path to "oci-arm-host-capacity" folder> index.php` in **Powershell** and got **error** with this output:

```php
PHP Fatal error:  Uncaught Dotenv\Exception\InvalidFileException: Failed to parse dotenv file. Encountered an unexpected escape sequence at ["C:\Users\prime\Documents\OCI keys\oci\prime.bridge.most@gmail.com_2023-05-05T13_46_48.939Z.pem"]. in C:\Users\prime\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Parser\Parser.php:30

Stack trace:
#0 C:\Users\prime\oci-arm-host-capacity\vendor\graham-campbell\result-type\src\Error.php(118): Dotenv\Parser\Parser::Dotenv\Parser\{closure}()
#1 C:\Users\prime\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Parser\Parser.php(29): GrahamCampbell\ResultType\Error->mapError()
#2 C:\Users\prime\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Dotenv.php(222): Dotenv\Parser\Parser->parse()
#3 C:\Users\prime\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Dotenv.php(237): Dotenv\Dotenv->load()
#4 C:\Users\prime\oci-arm-host-capacity\index.php(19): Dotenv\Dotenv->safeLoad()
#5 {main}
  thrown in C:\Users\prime\oci-arm-host-capacity\vendor\vlucas\phpdotenv\src\Parser\Parser.php on line 30
```

_**P.S.**_ Just replace `\` in path to your private key to `/`.

**Comment by SARCASMISH** [comment]
My error was fixed by moving "oci-arm-host-capacity" folder from `Users` folder to `C:/` folder, hope this will help someone!

**Comment by SARCASMISH** [comment]
My error was fixed by moving "oci-arm-host-capacity" folder from Users folder to C:/ folder, hope this will help someone!

**Comment by SARCASMISH** [comment]
My error was fixed by moving "oci-arm-host-capacity" folder from `Users` folder to `C:/` folder, hope this will help someone!
